const yaml = require('js-yaml')
const createJson = require('./create-json')
const pkg = require('../package.json')

module.exports = function createServerlessYml (domainId, options) {
  options = {
    clientId: process.env.CLIENT_NAME,
    stage: process.env.GIT_BRANCH,
    // TODO: version
    version: process.env.GIT_TAG,
    securityGroupIds: (process.env.SECURITY_GROUP_ID || '')
      .split(',')
      .filter(Boolean),
    subnetIds: (process.env.SUBNET_ID || '').split(',').filter(Boolean),
    ...options
  }
  console.log('[lib-domain] create yaml with options', options)
  const json = createJson(domainId, options)
  return [
    '###########################################',
    '# This file was generated by @ydv/lib-domain version ' + pkg.version,
    '# Do not commit this to source control.',
    '# If this requires changes, open a pull request in @ydv/lib-domain.',
    '###########################################',
    '',
    yaml.dump(json)
  ].join('\n')
}
